config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"

  get "new" => "users#new"

  post "new" => "users#create"

  get "login" => "users#login"

  get "users/create" => "users#create"

  post "login" => "sessions#create", as: :create_session

  get "sessions/show" => "sessions#show"

  get "sessions/destroy" => "sessions#destroy", as: :destroy_session

  get "teams/new" => "teams#new", as: :new_team

  post "teams/new" => "teams#create", as: :create_team

  get "teams/index" => "teams#index"

  get "teams/:id/edit" => "teams#edit", as: :edit_team

  patch "teams/:id/edit" => "teams#update", as: :update_team

  get "players/list" => "players#index"

  get "players/:id" => "players#show", as: :player

  get "players/:id/create" => "rosters#create", as: :create_roster

  get "teams/:id" => "teams#show", as: :team

  delete "players/:id" => "rosters#delete", as: :delete_roster

  namespace :api do
    resources :players, only: [:index, :show, :create, :update, :destroy]
  end

  namespace :api do
    resources :rosters, only: [:index]
  end

end

app/models/player.rb
class Player < ActiveRecord::Base
	validates :name, presence: true
  # belongs_to :team
  # belongs_to :user

  has_many :rosters
  has_many :teams, through: :rosters


end

app/models/roster.rb
class Roster < ActiveRecord::Base
  belongs_to :player
  belongs_to :team
end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :user
  has_many :rosters
  has_many :players, through: :rosters
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password
	has_one :team
	has_many :players

	validates :email, presence: true, uniqueness: {case_sensitive: false}

end

app/controllers/api/players_controller.rb
module API

	class PlayersController < ApplicationController

		def index
			render json: Player.all
		end

		def show
			render json: Player.find(params[:id])
		end

		def create
			player = Player.new(player_params)

			if player.save
				render json: player, status: 201, location: [:api, player]
			else
				render json: player.errors, status: 422
			end
		end

		def update
			player = Player.find(params[:id])

			if player.update(player_params)
				head 204
			else
				render json: player.errors, status: 422
			end
		end

		def destroy
			player = Player.find(params[:id])
			player.destroy
			head 204
		end

		private
		def player_params
			params.require(:player).permit(:name,:position,:r_team)
		end

	end

end

app/controllers/api/rosters_controller.rb
module API

	class RostersController < ApplicationController
		def index
			render json: Roster.all
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  def current_user
  	@current_user ||= User.find session[:user_id]  if session[:user_id]
  end

  protected  
  #this is where we create a method that returns a logged in user. 
  #This method will at first attempt to return the current user,
  #this is the @user part. The || says: OR if the @user doesn't exist, assign the result of User.find...
  #to @user, BUT, only attempt the User.find if there is a :user_id stored in the session.
	def current_user
  		@current_user ||= User.find session[:user_id]  if session[:user_id]
  	end

  def authorize
    unless current_user
       flash[:error] = "you must sign in first to go to that page"
       redirect_to new_session_path
    end
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

	def index
		# @playerz = Player.all

		if params[:query]
	  		search_field = params[:search].to_sym

	  		query = params[:query]
	  		player_list = Player.all
	  		@players = []
	        player_list.each do |player|
	        if player[search_field].downcase.include? query.downcase
	        	@players << player
	        end
	       	end
  		else 
    		@players = Player.page(params[:page]).per(50).padding(0)
    	end
    	@user = User.find(session[:id])
		@team  = @user.team
	end

	def show
		@user_id = session[:id]
		@player = Player.find(params[:id])
		@team = Team.find_by(user_id: @user_id)
		#conditional returns boolean if player is/isn't already on team
		if @team.players.include?(@player)
			@present = true
		else
			@present = false
		end
		@roster = Roster.where(player_id: @player)
		@user = User.find(session[:id])

	end

end

app/controllers/rosters_controller.rb
class RostersController < ApplicationController

	def new
		@roster = Roster.new
	end

	def create
		@roster_player_id = params[:id]
		#below code returns session id as number
		@user_id = session[:id]
		#uses session id to return specific user
		@user = User.find(@user_id)
		@team = @user.team
		
		@player = Player.find(@roster_player_id)
		#adds player to list of players on team
		@team.players << @player
		if @team.save
			redirect_to sessions_show_path
		else
			redirect_to sessions_show_path
		end
	end

	def show
		@roster = Roster.find(params[:id])
	end

	def delete
		@user_id = session[:id]
		@user = User.find(@user_id)
		@team = @user.team
		@player = Player.find(params[:id])
		@roster = Roster.find_by(player_id:@player.id,team_id: @team.id)
		@roster.delete
		redirect_to sessions_show_path
	end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		@user = User.find(session[:id])
	end

	def create
		@user = User.find_by(email: params[:email]).try(:authenticate, params[:password])

		if @user
			session[:id] = @user.id
			flash[:success] = 'you are signed in!'
			if @user.team
				redirect_to sessions_show_path
			else
				redirect_to new_team_path
			end
		else
			flash[:error] = 'unable to sign you in'
			redirect_to root_path
		end
	end

	def show
		@user = User.find(session[:id])
		@team  = @user.team
		#grabs ALL players in roster with corresponding team id
		@roster = Roster.where(team_id: @team).all
	end

	#logout
	def destroy
		session[:id] = nil
		flash[:error] = 'you have been logged out'
		redirect_to root_path
	end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

	def index	
		@teams = Team.all
		@user = User.find(session[:id])
		@team  = @user.team

	end

	def new
		@user = User.find(session[:id])
	end

	def create
		@team_name = params[:name]
		@team_user_id = params[:user_id]
		@team = Team.create({name: @team_name, user_id: @team_user_id})

		if @team.save
			redirect_to sessions_show_path
		else
			redirect_to sessions_show_path
		end
	end

	def show
		@team = Team.find(params[:id])
		@roster = Roster.where(team_id: @team).all
		@user = User.find(session[:id])
	end

	def edit
		@user = User.find(session[:id])
	end

	def update
		@team_name = params[:name]
		@team_user_id = params[:user_id]
		#below code finds the team that has user's id as team's id
		@team = Team.find_by(user_id: @team_user_id)
		#updates name of team grabbed above
		@team.update(name: @team_name)

		if @team.save
			redirect_to sessions_show_path
		else
			redirect_to sessions_show_path
		end		
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


	def create
		@user_name = params[:name]
		@user_email = params[:email]
		@user_password = params[:password]
		@user = User.create({name: @user_name, email: @user_email, password: @user_password})

		if @user.save
			flash[:success] = "You've successfully created an account"
			redirect_to create_session_path(@user)
		else
			flash[:error] = "Please try again"
			render :new
		end
	end

	def new
		@users = User.new
	end

	private
	def user_params
		params.require(:user).permit(:name,:email,:password,:password_confirmation)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/rosters_helper.rb
module RostersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <div class="container">
  <HEADER>
    <div class="page-header">
      <h1>FANtasy Tracker <small>Keep track of your favorite athletes</small></h1>
    </div>
  </HEADER>
</div>
  <body>

    <%= yield %>

  </body>
</html>

app/views/players/index.html.erb
<div class="container">

	<%= render "shared/nav" %>

	<h1>Players</h1>

	<br/>

	
		<%= form_tag('/players/list', method: "get") do %>
		Search player by:
		<%= select_tag "search", options_for_select(["name","position","r_team"]), class: "bar" %>
	    <%= text_field_tag :query, nil, class: "bar" %>
		<%= submit_tag "Search", "class" => "btn btn-primary" %>
		<% end %>

	
		<br/>

	  <% if @players.methods.include? :page %>
	    <%= paginate @players %>
	    <%end%>

	<br/>

	<div class="row">
		<div class="col-sm-12">
			<table>
			  <thead>
			    <tr>
			      <th class="tablehead">Name</th>
			      <th class="tablehead">Position</th>
			      <th class="tablehead">Team</th>
			    </tr>
			  </thead>
			  <tbody>
			  	<% @players.each do |x| %>
			    <tr>
			      <td class="tablerow"><%= link_to x.name, x %></td>
			      <td class="tablerow"><%= x.position %></td>
			      <td class="tablerow"><%= x.r_team %></td>
			    </tr>
			   <%end%>
			  </tbody>
			</table>
		</div>
	</div>

	<br/>
</div>

app/views/players/show.html.erb
<div class="container">

	<%= render "shared/nav" %>

	<div class="row">
		<div class="col-md-6">

			<h1><%= @player.name %></h1>

			<h3><%= @player.position %> - <%= @player.r_team %></h3>

			<!--uses conditional from controller to determine whether or not add button is viewable-->
			<% if @present %>
				<%= link_to	"Drop Player", delete_roster_path, method: :delete, class: "btn btn-warning" %>
			<% else %>
				<%= link_to "Add to Team", create_roster_path(team_id: @team), class: "btn btn-info" %>
			<%end%>
		</div>	

		<div class="col-md-6">
			<a href="#" class="thumbnail">
			    <img src="http://a.espncdn.com/combiner/i?img=/i/headshots/mlb/players/full/3246.png&w=350&h=254">
			</a>	  
		</div>
		
	</div>

	<br/>

	<%= render "shared/stat" %>

	<br/>

	<h4>Teams</h4>
	<ul class="list-group">
		<% @roster.each do |x| %>
		<li class="list-group-item" style="font-size:medium"><%= link_to x.team.name, x.team  %></li>
		<%end%>
	</ul>

	<br/>

	<%= link_to "Back", players_list_path, class: "btn btn-danger" %>

</div>

app/views/shared/_nav.html.erb
	<div class="icon-bar five-up">
	  <a class="item" href="<%= sessions_show_path %>">
	    <i class="fi-home"></i>
	    <label>Home</label>
	  </a>
	  <a class="item" href="<%= edit_team_path(@user.team) %>">
	  	<i class="fi-widget"></i>
	  	<label>Settings</label>
	  </a>
	  <a class="item" data-dropdown="drop">
	  	<i class="fi-list"></i>
	    <label>View</label>
	    	<ul id="drop" class="small f-dropdown" data-dropdown-content>
	    		<li style="font-size:large"><a href="<%= teams_index_path %>">All Teams</a></li>
	    		<li style="font-size:large"><a href="<%= players_list_path %>">All Players</a></li>
	    	</ul>
	  </a>
	  <a class="item">
	    <i class="fi-mail"><span class="badge">4</span></i>
	    <label>Messages</label>
	  </a>
	  <a class="item">
	  	<i class="fi-like"><span class="badge">12</span></i>
	    <label>Likes</label>
	  </a>
	</div>

app/views/shared/_stat.html.erb
<h4>Stats</h4>
	<table class="table table-bordered">
		<thead>
			<tr>
				<th style="font-size:medium">Year</th>
				<th style="font-size:medium">BA</th>
				<th style="font-size:medium">HR</th>
				<th style="font-size:medium">RBI</th>
				<th style="font-size:medium">OBP</th>
				<th style="font-size:medium">SLG</th>
			</tr>	
		</thead>
		<tbody>
			<tr>	
				<th style="font-size:medium">2015</th>
				<th style="font-size:medium">.349</th>
				<th style="font-size:medium">24</th>
				<th style="font-size:medium">102</th>
				<th style="font-size:medium">.438</th>
				<th style="font-size:medium">.552</th>
			</tr>
		</tbody>
	</table>

app/views/users/login.html.erb
<div class="container">

<div class="row">	
	<div class="col-md-1">
	</div>
	<div class="panel panel-primary col-md-10">
		<h4>Login</h4>

		<br/>

		<% flash.each do |key,value|  %>
		    <div class="<%= key %>" > <%= value %> </div>
		<% end %>

		<br/>

		<%= form_for :user, url: create_session_path do %>
			<div class="row">
			  <label class="col-sm-2 col-md-2 control-label">Email</label>
			  <div class="col-sm-8"><%= email_field_tag :email, nil, placeholder: "Email", class: "form-control" %>
		  	  </div>
		  	</div>
		  	<div class="row">
			  <label class="col-sm-2 col-md-2 control-label">Password</label>
			  <div class="col-sm-8"><%= password_field_tag :password, nil, placeholder: "Password", class: "form-control" %>
			 	</div>
			<div class="row">

			<div class="col-sm-offset-4 col-sm-10">
		  		<%= submit_tag "Sign In", class: "btn btn-primary" %>
		<% end %>
				<%= link_to "Back", root_path, class: "btn btn-danger" %>
		    </div>
			</div>
			</div>	
		</div>
</div>

app/views/users/new.html.erb
<div class="container">

	<div class="panel panel-primary col-md-10">
		<h4>Sign Up</h4>

		<br/>

		<% flash.each do |key,value|  %>
			<div class="<%= key %>" > <%= value %> </div>
		<% end %>

		<%= form_for :user, url: new_path do %>
		  <label class="col-sm-2 control-label">Name</label>
		  	<div class="col-sm-10"><%= text_field_tag :name, nil, placeholder: "Name", class: "form-control", style: "height:32px" %></div>
		  <label class="col-sm-2 control-label">Email</label>
		    <div class="col-sm-10"><%= email_field_tag :email, nil, placeholder: "Email", class: "form-control", style: "height:32px" %></div>
		  <label class="col-sm-2 control-label">Password</label>
		    <div class="col-sm-10"><%= password_field_tag :password, nil, placeholder: "Password", class: "form-control", style: "height:32px" %></div>
		  <label class="col-sm-2 control-label">Confirm Password</label>
		    <div class="col-sm-10"><%= password_field_tag :password_confirmation, nil, placeholder: "Password Confirm", class: "form-control", style: "height:32px" %></div>
		  <div class="col-sm-offset-2 col-sm-10">
		  	<%= submit_tag "Sign Up!", class: "btn btn-primary" %>
		<% end %>
		  	<%= link_to "Back", root_path, class: "btn btn-danger" %>
		  </div>	
	</div>

</div>

app/views/welcome/index.html.erb
<div class="container" id="home">

	<!-- Warming Up -->
<!-- <link href='http://fonts.googleapis.com/css?family=Buenard:700' rel='stylesheet' type='text/css'>
<script src="http://pupunzi.com/mb.components/mb.YTPlayer/demo/inc/jquery.mb.YTPlayer.js"></script> -->

<!--Video Section-->
<!-- <section class="content-section video-section">
  <div class="pattern-overlay">
  <a id="bgndVideo" class="player" data-property="{videoURL:'https://www.youtube.com/watch?v=n2DmVV_Gunk',containment:'.video-section', quality:'large', autoPlay:true, mute:true, opacity:1}">bg</a>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
        <h1>Full Width Video</h1>  
        <h3>Enjoy Adding Full Screen Videos to your Page Sections</h3>
	   </div>
      </div>
    </div>
  </div>
</section> -->
<!--Video Section Ends Here-->

	<div class="jumbotron">
  		<h1>Welcome to FANtasy Tracker!</h1>
			<p>
			  Keep track of your favorite teams, players, and fantasy teams in one place.  Share your favorites and
			  remind your friends when their teams suck!
			</p>
	</div>

	<br/>

	<div class="row">
		<div class="col-md-3">
		</div>
			<div class="panel panel-primary col-md-6">
				<div class="panel-body">
					New Users<br/>
					<%= link_to "Sign Up", new_path, class: "btn btn-primary" %><br/>
					Have an account?<br/>
					<%= link_to "Login", login_path, class: "btn btn-danger" %><br/>
				</div>
			</div>
		
	</div>
</div>